# Generated by Django 5.1.7 on 2025-03-29 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardboard', models.IntegerField(default=0)),
                ('food_organics', models.IntegerField(default=0)),
                ('glass', models.IntegerField(default=0)),
                ('metal', models.IntegerField(default=0)),
                ('miscellaneous_trash', models.IntegerField(default=0)),
                ('paper', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
